# Basic Information 
title: Ming Zhang
# position: Masterâ€™s Student at Renmin University
# affiliation: Renmin University of China
email: jonnierzhang@foxmail.com

# Search Engine Optimization
keywords: statistics, machine learning, AI, causal inference
description: Ming Zhang is a Master student in Statistics and AI at Renmin University of China.
canonical: https://zhangming4153.github.io/

# Links 
# cv_link: assets/files/CV_MingZhang_en.pdf
# github_link: https://github.com/zhangming4153

# Images 
avatar: ./assets/img/profile.png
favicon: ./assets/img/renmin.png
favicon_dark: ./assets/img/renmin.png

enable_footnote: false
auto_dark_mode: true
font: "Serif"

# Google Analytics
google_analytics: G-0DKF7N1ZZH  

remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
